<?php
/**
 * Template for Mage_Adminhtml_Block_Catalog_Product_Edit
 * Template for Learn_Autosku_Block_Adminhtml_Catalog_Product_Edit
 */
?>

<!-- <h1><?php echo $this->__('New Product (Auto Sku)');?> :</h1> -->

<div class="content-header">
    <h3 class="icon-head head-products"><?php echo $this->getHeader() ?></h3>
    <p class="content-buttons form-buttons"><?php echo $this->getBackButtonHtml() ?>
        <?php echo $this->getCancelButtonHtml() ?>
        <?php if($this->getProductId()): ?>
        <?php echo $this->getDeleteButtonHtml() ?>
        <?php if($this->getProductSetId() && $this->getIsConfigured()): ?>
        <?php echo $this->getDuplicateButtonHtml() ?>
    <?php endif; ?>
<?php endif; ?>
<?php if($this->getProductSetId() && $this->getIsConfigured()): ?>
    <?php echo $this->getSaveButtonHtml() ?>
    <?php echo $this->getSaveAndEditButtonHtml() ?>
<?php endif; ?>
</p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="product_edit_form" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<div style="display:none"></div>


<script type="text/javascript">
//<![CDATA[
var productTemplateSyntax = /(^|.|\r|\n)({{(\w+)}})/;
var productForm = new varienForm('product_edit_form', '<?php echo $this->getValidationUrl() ?>');
productForm._processValidationResult = function(transport) {
    var response = transport.responseText.evalJSON();
    if (response.error){
        if (response.attribute && $(response.attribute)) {
            $(response.attribute).setHasError(true, productForm);
            Validation.ajaxError($(response.attribute), response.message);
            if (!Prototype.Browser.IE){
                $(response.attribute).focus();
            }
        }
        else if ($('messages')) {
            $('messages').innerHTML = '<ul class="messages"><li class="error-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
        }
    }
    else{
        productForm._submit();
    }
};
function saveAndContinueEdit(urlTemplate) {
    var template = new Template(urlTemplate, productTemplateSyntax);
    var url = template.evaluate({tab_id:product_info_tabsJsTabs.activeTab.id});
    productForm.submit(url);
}
function setSettings(urlTemplate, setElement, typeElement) {
    var template = new Template(urlTemplate, productTemplateSyntax);
    setLocation(template.evaluate({attribute_set:$F(setElement),type:$F(typeElement)}));
    }

    function setSuperSettings(urlTemplate, attributesClass, validateField) {
        var attributesFields = $$('.' + attributesClass);
        var attributes = Form.serializeElements(attributesFields, true).attribute;
        if(typeof attributes == 'string') {
            attributes = [attributes];
        }

        if(!attributes) {
            $(validateField).value = 'no-attributes';
        } else {
            $(validateField).value = 'has-attributes';
        }

        if (productForm.validator.validate()) {
            var template = new Template(urlTemplate, productTemplateSyntax);
            var url = template.evaluate({
                attributes: encode_base64(attributes.join(',')).replace(new RegExp('/','g'),'%2F').replace(new RegExp('=','g'),'%3D')
            });
            setLocation(url);
        }
    }

    function checkMaxLength(Object, MaxLen)
    {
        if (Object.value.length > MaxLen-1) {
            Object.value = Object.value.substr(0, MaxLen);
        }
        return 1;
    }

    Event.observe(window, 'load', function() {
        var objName = '<?php echo $this->getSelectedTabId() ?>';
        if (objName) {
            obj = $(objName);
        //IE fix (bubbling event model)
        product_info_tabsJsTabs.setSkipDisplayFirstTab();
        product_info_tabsJsTabs.showTabContent(obj);
    }
    Product.AttributesBridge.setTabsObject(product_info_tabsJsTabs);
});

    Validation.addAllThese([
        ['validate-super-product-attributes', '<?php echo Mage::helper('catalog')->__('Please select one or more attributes.') ?>', function(v) {
            return (v != "no-attributes");
        }]]);
//]]>
</script>

<?php
/* $getprevEntityId = $this->getprevEntityId(); */
$skuautores = $this->skuAuto($this->getRequest()->getParam('type'));

?>

<script type="text/javascript">
    if(document.getElementById('sku')) {
        if(document.getElementById('sku').value == "") {
           var finalskustring = "<?php echo $skuautores; ?>";
        } else {
            var finalskustring = document.getElementById('sku').value;    
        }
        
        //Code to place sku in text box
        var innermyspan = $('sku').parentNode.innerHTML;
        $('sku').parentNode.innerHTML = innermyspan+'<input type="checkbox" class="checkbox" onclick="toggleValueElements(this, this.parentNode);istoggle();" checked="checked" value="1" name="isauto" id="isauto">';
        document.getElementById('sku').value =finalskustring;
        toggleValueElements($('isauto'), $('isauto').parentNode);
    }

    function removeCheck() {
        if(document.getElementById('sku').value != "") {
            if(document.getElementById("isauto"))
                document.getElementById("isauto").checked = false;
            document.getElementById('sku').disabled = false;
        }
    }

    function istoggle(){
        if(document.getElementById('isauto').checked){
            document.getElementById('sku').value = finalskustring;
        }
    }
</script> 
